// src/lib/components/modals/HighschoolModal.tsx
export function HighschoolModal() {
	return (
		<div className="modal-detail-content">
			<h3>横浜市立横浜サイエンスフロンティア高等学校</h3>
			<p>
				2020年4月から2023年3月まで在籍。通称「サイフロ」。
				SSH（スーパーサイエンスハイスクール）指定校として、科学技術や理数系教育に特化した教育を受けました。
			</p>

			<h3>学んだこと</h3>
			<ul>
				<li>
					<strong>プログラミング</strong>:
					高校在学中にFlutter/Dartでのモバイルアプリ開発を独学で習得
				</li>
				<li>
					<strong>研究活動</strong>:
					サイエンスリテラシーの授業を通じて、科学的思考法と研究手法を学習
				</li>
				<li>
					<strong>チーム開発</strong>:
					文化祭でのプロダクト開発を通じてチーム開発の経験を積む
				</li>
			</ul>

			<h3>主な活動・成果</h3>
			<ul>
				<li>EQMonitor の開発開始（2021年〜）</li>
				<li>文化祭でのプリントシール機開発プロジェクト</li>
				<li>各種プログラミングコンテストへの参加</li>
			</ul>

			<h3>この高校を選んだ理由</h3>
			<p>
				科学技術に興味があり、実験や研究活動が充実している環境で学びたいと考えていました。
				SSHの指定校であることから、最先端の科学技術に触れる機会が多く、
				自分の興味を深めることができる環境だと感じて入学を決めました。
			</p>
		</div>
	);
}

// src/lib/components/modals/HighschoolModal.svelte
<div class="modal-detail-content">
	<h3>横浜市立横浜サイエンスフロンティア高等学校</h3>
	<p>
		2020年4月から2023年3月まで在籍。通称「サイフロ」。
		SSH（スーパーサイエンスハイスクール）指定校として、科学技術や理数系教育に特化した教育を受けました。
	</p>

	<h3>学んだこと</h3>
	<ul>
		<li><strong>プログラミング</strong>: 高校在学中にFlutter/Dartでのモバイルアプリ開発を独学で習得</li>
		<li><strong>研究活動</strong>: サイエンスリテラシーの授業を通じて、科学的思考法と研究手法を学習</li>
		<li><strong>チーム開発</strong>: 文化祭でのプロダクト開発を通じてチーム開発の経験を積む</li>
	</ul>

	<h3>主な活動・成果</h3>
	<ul>
		<li>EQMonitor の開発開始（2021年〜）</li>
		<li>文化祭でのプリントシール機開発プロジェクト</li>
		<li>各種プログラミングコンテストへの参加</li>
	</ul>

	<h3>この高校を選んだ理由</h3>
	<p>
		科学技術に興味があり、実験や研究活動が充実している環境で学びたいと考えていました。
		SSHの指定校であることから、最先端の科学技術に触れる機会が多く、
		自分の興味を深めることができる環境だと感じて入学を決めました。
	</p>
</div>

<style>
	.modal-detail-content {
		line-height: 1.8;
	}

	.modal-detail-content h3 {
		margin-top: 1.5rem;
		margin-bottom: 0.75rem;
		font-size: 1.25rem;
		color: var(--color-text);
		padding-left: 0;
	}

	.modal-detail-content h3:first-child {
		margin-top: 0;
	}

	.modal-detail-content h3::before {
		content: none;
	}

	.modal-detail-content p {
		margin-bottom: 1rem;
		color: var(--color-text);
	}

	.modal-detail-content ul {
		margin-bottom: 1rem;
		padding-left: 1.5rem;
	}

	.modal-detail-content li {
		margin-bottom: 0.5rem;
	}
</style>
